= μacme
:proj-name: muacme
:gh-name: jirutka/{proj-name}
:version: 0.3.1

This a convenient wrapper for the ACMEv2 client https://github.com/ndilieto/uacme[uacme] that provides a ready-to-go solution for a cron-based periodic renewal of an arbitrary number of TLS certificates.


== Requirements

* https://github.com/ndilieto/uacme[uacme]
* http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html[POSIX-sh] compatible shell with `pipefail` (e.g. Busybox ash, ZSH, bash, …)
* `grep`, `sed`, `tr`, `xargs` (BSD, Busybox or GNU)
* `openssl` command (should work with OpenSSL and LibreSSL)


== Installation

[source, sh, subs="+attributes"]
wget https://github.com/{gh-name}/archive/v{version}/{proj-name}-{version}.tar.gz
tar -xzf {proj-name}-{version}.tar.gz
cd {proj-name}-{version}
make install


== Usage

See the help section in link:muacme#L3[muacme] (or run `muacme -h`) and comments in link:muacme.conf[].

Note that you have to create an ACME account first (see https://ndilieto.github.io/uacme/uacme.html#_usage[uacme(1)] for more information):

[source]
uacme -v -c /etc/ssl/uacme new [EMAIL]


== Examples

* Issue a certificate for domain _foo.example.org_ with alternative name _bar.example.org_ and options specified in the configuration file _/etc/muacme/muacme.conf_:
+
[source, sh]
muacme issue example.org www.example.org

* Issue a certificate for each domain listed in the given file (one per line with optional alternative names separated by a space) for which we don’t have it already:
+
[source,sh]
muacme issue -F domains.list

* Renew all certificates that are close to their expiration:
+
[source, sh]
muacme renew all

* Renew certificate for domain _foo.example.org_ even if it’s too soon:
+
[source, sh]
muacme renew -f foo.example.org

* A renew hook for reloading nginx on a system using OpenRC:
+
[source, sh]
#!/bin/sh
/etc/init.d/nginx --ifstarted --quiet reload

* A cron script _/etc/periodic/weekly/muacme-renew-all_:
+
[source, sh]
#!/bin/sh
exec muacme renew -l all


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.


== See Also

* https://ndilieto.github.io/uacme/[uacme(1)]
